### ISSUE TITLE
[Feature] Laravel or Composer package

### ISSUE THREAD

**Issue by ghost** [JPinkney/TVMaze-PHP-API-Wrapper#1]
Hi, can you create a laravel package or just a composer package ?

Thanks

**Comment by ghost** [comment]
Hello

**Comment by niel** [comment]
Adding my voice to this request. I see the composer.json in the repo, but Composer cannot install it, maybe you need to add it to Packagist?

**Comment by JPinkney** [comment]
I'll take a look into it on the weekend. I'm really busy right now and I honestly have no idea how to use Composer. I usually don't develop in php so uploading it to composer and putting it on packagist is completely new

**Comment by niel** [comment]
I'd be willing to help. I did get it working using the composer.json file that you have now deleted :-(

**Comment by niel** [comment]
Just looked at Packagist. It seems that all that is needed is to restore your composer.json file, create an account at Packagist, then submit the url to the package via https://packagist.org/packages/submit. The rest of the info needed is taken from the composer.json file.

**Comment by niel** [comment]
There are other thing you could do to improve the support, but they would be for future consideration.

**Comment by JPinkney** [comment]
I've just reverted back to the old composer.json. I can get it on packagist but it gives me some "Could not find package at any version for your minimum-stability" error when I tried to do "composer require joshpinkney/tv-maze-php-api" so I feel like my composer.json is wrong? Unfortunately i've only really used php for one project so I have a very small understanding of how all this works

**Comment by JPinkney** [comment]
Heres the packagist link if you know anything about it https://packagist.org/packages/joshpinkney/tv-maze-php-api

**Comment by ghost** [comment]
@JPinkney  you can run composer like `composer require joshpinkney/tv-maze-php-api dev-master`

or you could try to change `"minimum-stability": "beta",` to `"minimum-stability": "dev",` in your composer.json

and see if it works

**Comment by niel** [comment]
Many thanks. it is working fine for me now.
I would say you can close this issue now.
